name: Build Status Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Service Registry
      run: |
        if [ -d "service-registory" ]; then
          cd service-registory
          mvn clean install -DskipTests
        else
          echo "Service Registry directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Build Auth Service
      run: |
        if [ -d "services/auth-service" ]; then
          cd services/auth-service
          mvn clean install -DskipTests
        else
          echo "Auth Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Pet Service
      run: |
        if [ -d "services/pet-service" ]; then
          cd services/pet-service
          go build -v ./...
        else
          echo "Pet Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Build Billing Service
      run: |
        if [ -d "services/billing-service" ]; then
          cd services/billing-service
          go build -v ./...
        else
          echo "Billing Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Build Owner Service
      run: |
        if [ -d "services/owner-service" ]; then
          cd services/owner-service
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          echo "Python Owner Service build check completed"
        else
          echo "Owner Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Build Notification Service
      run: |
        if [ -d "services/notification-service" ]; then
          cd services/notification-service
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          echo "Python Notification Service build check completed"
        else
          echo "Notification Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Build Vet Service
      run: |
        if [ -d "services/vet-service" ]; then
          cd services/vet-service
          if [ -f "package.json" ]; then
            npm ci
            npm run build --if-present
          fi
          echo "Node.js Vet Service build check completed"
        else
          echo "Vet Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    # Add more services here as they are added to the project
    
    - name: Update PR with build status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.issue;
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: '✅ All services build successfully!'
          });
