name: Java Services CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'service-registory/**'
      - 'services/auth-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'service-registory/**'
      - 'services/auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['service-registory', 'services/auth-service']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        cd ${{ matrix.service }}
        mvn clean install -DskipTests
        
    - name: Run Tests
      run: |
        cd ${{ matrix.service }}
        mvn test
